development:
  adapter: postgresql
  database: medapulse_dev
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: medapulse_staging
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: medapulse_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: medapulse_prod
  pool: 5
  timeout: 5000

cucumber:
  <<: *test